services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/data:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e development -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/api
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-mybucket}
      MINIO_ENDPOINT: http://minio.${HOST_IP:-127.0.0.1}.nip.io:9000
    ports:
      - '3000:3000'
    depends_on:
      - db
    stdin_open: true
    tty: true
  
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - ${MINIO_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9001}:9001
    volumes:
      - ./minio/data:/export
      - ./minio/config:/root/.minio
    environment:
      MINIO_DOMAIN: minio.${HOST_IP:-127.0.0.1}.nip.io
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
    command: server /export --console-address ":9001"
    networks:
      default:
        aliases:
          - minio.${HOST_IP:-127.0.0.1}.nip.io
          - file.minio.${HOST_IP:-127.0.0.1}.nip.io

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        until (/usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER:-minio} ${MINIO_ROOT_PASSWORD:-minio123}) do
          echo '...waiting...' && sleep 1;
        done;

        /usr/bin/mc mb -p myminio/${MINIO_BUCKET_NAME:-mybucket};
        /usr/bin/mc anonymous set download myminio/${MINIO_BUCKET_NAME:-mybucket};

        exit 0;
      "

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  # Vite dev server
    volumes:
      - ./frontend/app:/app
    env_file:
      - .env
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - api